"""initial

Revision ID: 07397603f166
Revises: 
Create Date: 2026-05-11 16:31:19.195522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07397603f166'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('smmlv', sa.Numeric(precision=12, scale=2), nullable=False, comment='Salario Mínimo Mensual Legal Vigente 2026'),
    sa.Column('auxilio_transporte', sa.Numeric(precision=12, scale=2), nullable=False, comment='Auxilio de transporte mensual 2026'),
    sa.Column('festivos', sa.Text(), nullable=False, comment="Lista de fechas festivas en formato JSON: ['2026-01-01', '2026-01-12', ...]"),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('documento', sa.String(length=50), nullable=False),
    sa.Column('salario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empleados_documento'), 'empleados', ['documento'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'CONTADOR', 'EMPLEADO', name='rol_usuario', create_constraint=True), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('ciclo_rotacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_inicio_ciclo', sa.Date(), nullable=False, comment='Fecha de inicio del ciclo (debe ser un lunes)'),
    sa.Column('empleado_a_id', sa.Integer(), nullable=False),
    sa.Column('empleado_b_id', sa.Integer(), nullable=False),
    sa.Column('empleado_c_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Solo 1 registro activo a la vez'),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empleado_a_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['empleado_b_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['empleado_c_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marcaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('timestamp_entrada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_salida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('horas_efectivas', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fuente', sa.String(length=20), nullable=False, comment='Origen: FORM (Google Forms via Make) o MANUAL (corrección admin)'),
    sa.Column('corregido_por', sa.Integer(), nullable=True),
    sa.Column('nota_correccion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corregido_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_id', 'fecha', name='idx_marcacion_empleado_fecha')
    )
    op.create_index(op.f('ix_marcaciones_empleado_id'), 'marcaciones', ['empleado_id'], unique=False)
    op.create_table('nomina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('dias_habiles_quincena', sa.Integer(), nullable=False),
    sa.Column('dias_habiles_mes', sa.Integer(), nullable=False),
    sa.Column('umbral_horas', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_horas_trabajadas', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('total_devengado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_deducciones', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('neto_pagar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('aprobado_por', sa.Integer(), nullable=True),
    sa.Column('aprobado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nomina_empleado_id'), 'nomina', ['empleado_id'], unique=False)
    op.create_table('detalle_nomina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomina_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=80), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('horas', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('porcentaje', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['nomina_id'], ['nomina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_nomina_nomina_id'), 'detalle_nomina', ['nomina_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_nomina_nomina_id'), table_name='detalle_nomina')
    op.drop_table('detalle_nomina')
    op.drop_index(op.f('ix_nomina_empleado_id'), table_name='nomina')
    op.drop_table('nomina')
    op.drop_index(op.f('ix_marcaciones_empleado_id'), table_name='marcaciones')
    op.drop_table('marcaciones')
    op.drop_table('ciclo_rotacion')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_empleados_documento'), table_name='empleados')
    op.drop_table('empleados')
    op.drop_table('configuracion')
    # ### end Alembic commands ###
