"""add_missing_tables

Revision ID: a5e8ccabad8e
Revises: initial_001
Create Date: 2026-05-09 17:21:50.177723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e8ccabad8e'
down_revision: Union[str, None] = 'initial_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciclo_rotacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_inicio_ciclo', sa.Date(), nullable=False, comment='Fecha de inicio del ciclo (debe ser un lunes)'),
    sa.Column('empleado_a_id', sa.Integer(), nullable=False),
    sa.Column('empleado_b_id', sa.Integer(), nullable=False),
    sa.Column('empleado_c_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Solo 1 registro activo a la vez'),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empleado_a_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['empleado_b_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['empleado_c_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marcaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('timestamp_entrada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_salida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('horas_efectivas', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fuente', sa.String(length=20), nullable=False, comment='Origen: FORM (Google Forms via Make) o MANUAL (corrección admin)'),
    sa.Column('corregido_por', sa.Integer(), nullable=True),
    sa.Column('nota_correccion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corregido_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_id', 'fecha', name='idx_marcacion_empleado_fecha')
    )
    op.create_index(op.f('ix_marcaciones_empleado_id'), 'marcaciones', ['empleado_id'], unique=False)
    op.create_table('nomina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('dias_habiles_quincena', sa.Integer(), nullable=False),
    sa.Column('dias_habiles_mes', sa.Integer(), nullable=False),
    sa.Column('umbral_horas', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_horas_trabajadas', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('total_devengado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_deducciones', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('neto_pagar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('aprobado_por', sa.Integer(), nullable=True),
    sa.Column('aprobado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nomina_empleado_id'), 'nomina', ['empleado_id'], unique=False)
    op.create_table('detalle_nomina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomina_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=80), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('horas', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('porcentaje', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['nomina_id'], ['nomina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_nomina_nomina_id'), 'detalle_nomina', ['nomina_id'], unique=False)
    op.alter_column('configuracion', 'smmlv',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Salario Mínimo Mensual Legal Vigente 2026',
               existing_nullable=False,
               existing_server_default=sa.text('1423500.00'))
    op.alter_column('configuracion', 'auxilio_transporte',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Auxilio de transporte mensual 2026',
               existing_nullable=False,
               existing_server_default=sa.text('200000.00'))
    op.alter_column('configuracion', 'festivos',
               existing_type=sa.TEXT(),
               comment="Lista de fechas festivas en formato JSON: ['2026-01-01', '2026-01-12', ...]",
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::text"))
    op.drop_constraint('empleados_documento_key', 'empleados', type_='unique')
    op.drop_index('ix_empleados_documento', table_name='empleados')
    op.create_index(op.f('ix_empleados_documento'), 'empleados', ['documento'], unique=True)
    op.drop_constraint('usuarios_email_key', 'usuarios', type_='unique')
    op.drop_index('ix_usuarios_email', table_name='usuarios')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=False)
    op.create_unique_constraint('usuarios_email_key', 'usuarios', ['email'])
    op.drop_index(op.f('ix_empleados_documento'), table_name='empleados')
    op.create_index('ix_empleados_documento', 'empleados', ['documento'], unique=False)
    op.create_unique_constraint('empleados_documento_key', 'empleados', ['documento'])
    op.alter_column('configuracion', 'festivos',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Lista de fechas festivas en formato JSON: ['2026-01-01', '2026-01-12', ...]",
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::text"))
    op.alter_column('configuracion', 'auxilio_transporte',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Auxilio de transporte mensual 2026',
               existing_nullable=False,
               existing_server_default=sa.text('200000.00'))
    op.alter_column('configuracion', 'smmlv',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Salario Mínimo Mensual Legal Vigente 2026',
               existing_nullable=False,
               existing_server_default=sa.text('1423500.00'))
    op.drop_index(op.f('ix_detalle_nomina_nomina_id'), table_name='detalle_nomina')
    op.drop_table('detalle_nomina')
    op.drop_index(op.f('ix_nomina_empleado_id'), table_name='nomina')
    op.drop_table('nomina')
    op.drop_index(op.f('ix_marcaciones_empleado_id'), table_name='marcaciones')
    op.drop_table('marcaciones')
    op.drop_table('ciclo_rotacion')
    # ### end Alembic commands ###
